#!/usr/bin/env python3
"""`cmd` for the two batch files node-pty's winpty.gyp runs at gyp time.

node-pty 1.1.0-beta1's deps/winpty/src/winpty.gyp computes, while gyp loads it,
  WINPTY_COMMIT_HASH%  = <!(cmd /c "cd shared && GetCommitHash.bat")
  include_dirs        += <!(cmd /c "cd shared && UpdateGenVersion.bat <hash>")
which need the Windows command interpreter; the cross build runs gyp on Linux.
This program performs exactly what those two batch files do and nothing else
(any other command is an error):
  GetCommitHash.bat      prints `git rev-parse HEAD` run in shared\ (the HEAD of
                         whatever checkout encloses the module, as on Windows),
                         or "none" when that fails.
  UpdateGenVersion.bat H writes ..\\gen\\GenVersion.h -- an AUTO-GENERATED
                         comment line, GenVersion_Version = the first line of
                         ..\\..\\VERSION.txt, GenVersion_Commit = H -- and prints
                         "gen" (the include directory, relative to src).
winpty's own POSIX build generates the same header from the same inputs
(deps/winpty/Makefile: build/gen/GenVersion.h rule; configure: COMMIT_HASH).
"""

import os
import re
import subprocess
import sys


def main():
  if len(sys.argv) != 3 or sys.argv[1].lower() != '/c':
    sys.exit('winpty_cmd.py: unsupported command line: %r' % sys.argv[1:])
  m = re.match(r'^cd (\S+) && (GetCommitHash|UpdateGenVersion)\.bat(?: (\S+))?$',
               sys.argv[2].strip())
  if not m:
    sys.exit('winpty_cmd.py: unsupported command: %r' % sys.argv[2])
  os.chdir(m.group(1))
  if m.group(2) == 'GetCommitHash':
    if m.group(3) is not None:
      sys.exit('winpty_cmd.py: GetCommitHash.bat takes no argument')
    try:
      print(subprocess.check_output(['git', 'rev-parse', 'HEAD'],
                                    stderr=subprocess.DEVNULL,
                                    universal_newlines=True).strip())
    except (OSError, subprocess.CalledProcessError):
      print('none')
    return 0
  commit = m.group(3) or ''
  with open(os.path.join('..', '..', 'VERSION.txt')) as f:
    version = f.readline().rstrip('\r\n')  # `set /p VERSION=<file`
  os.makedirs(os.path.join('..', 'gen'), exist_ok=True)
  with open(os.path.join('..', 'gen', 'GenVersion.h'), 'w', newline='\r\n') as f:
    f.write('// AUTO-GENERATED BY UpdateGenVersion.bat %s\n' % commit)
    f.write('const char GenVersion_Version[] = "%s";\n' % version)
    f.write('const char GenVersion_Commit[] = "%s";\n' % commit)
  print('gen')
  return 0


if __name__ == '__main__':
  sys.exit(main())
